# Generated by Django 5.1 on 2024-08-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenWear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=4)),
                ('mrp', models.CharField(max_length=4)),
                ('image_link', models.URLField()),
                ('last_7_day_sale', models.IntegerField()),
                ('fit', models.CharField(max_length=50)),
                ('fabric', models.CharField(max_length=50)),
                ('neck', models.CharField(max_length=20, null=True)),
                ('sleeve', models.CharField(max_length=50, null=True)),
                ('pattern', models.CharField(max_length=50, null=True)),
                ('length', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=400)),
                ('links', models.JSONField(null=True)),
                ('available_skus', models.JSONField(null=True)),
            ],
        ),
    ]
