# Generated by Django 5.1 on 2024-08-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menwear',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='fabric',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='fit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='image_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='last_7_day_sale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='length',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='mrp',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='price',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='menwear',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
